config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'welcome/index'

  root 'welcome#index'
  get 'welcome/flot' => 'welcome#flot', as: :flot
  get 'welcome/morris' => 'welcome#morris', as: :morris
  get 'welcome/tables' => 'welcome#tables', as: :tables
  get 'welcome/forms' => 'welcome#forms', as: :forms
  get 'welcome/panels_wells' => 'welcome#panels_wells', as: :panels_wells
  get 'welcome/buttons' => 'welcome#buttons', as: :buttons
  get 'welcome/notifications' => 'welcome#notifications', as: :notifications
  get 'welcome/typography' => 'welcome#typography', as: :typography
  get 'welcome/icons' => 'welcome#icons', as: :icons
  get 'welcome/grid' => 'welcome#grid', as: :grid
  get 'welcome/blank' => 'welcome#blank', as: :blank
  get 'welcome/login' => 'welcome#login', as: :login

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  layout :layout_by_resource

private
  def layout_by_resource
    if devise_controller?
      "login"
    else
      "application"
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def flot
  end

  def morris
  end

  def tables
  end

  def forms
  end


  def panels_wells
  end

  def buttons
  end

  def notifications
  end

  def typography
  end

  def icons
  end

  def grid
  end

  def blank
  end

  def login
    render layout: 'login'
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_alerts.html.haml
- if notice
  .alert.alert-success.alert-dismissable
    %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} ×
    = notice
    / = succeed "." do
    /   %a.alert-link{:href => "#"} Alert Link
- if alert
  .alert.alert-danger.alert-dismissable
    %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} ×
    = alert
    / = succeed "." do
    /   %a.alert-link{:href => "#"} Alert Link

app/views/layouts/_nav.html.haml
.navbar-header
  %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
    %span.sr-only Toggle navigation
    %span.icon-bar
    %span.icon-bar
    %span.icon-bar
  %a.navbar-brand{:href => "index.html"} SB Admin v2.0
/ /.navbar-header
%ul.nav.navbar-top-links.navbar-right
  %li.dropdown
    %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
      %i.fa.fa-envelope.fa-fw
      %i.fa.fa-caret-down
    %ul.dropdown-menu.dropdown-messages
      %li
        %a{:href => "#"}
          %div
            %strong John Smith
            %span.pull-right.text-muted
              %em Yesterday
          %div Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eleifend...
      %li.divider
      %li
        %a{:href => "#"}
          %div
            %strong John Smith
            %span.pull-right.text-muted
              %em Yesterday
          %div Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eleifend...
      %li.divider
      %li
        %a{:href => "#"}
          %div
            %strong John Smith
            %span.pull-right.text-muted
              %em Yesterday
          %div Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eleifend...
      %li.divider
      %li
        %a.text-center{:href => "#"}
          %strong Read All Messages
          %i.fa.fa-angle-right
    / /.dropdown-messages
  / /.dropdown
  %li.dropdown
    %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
      %i.fa.fa-tasks.fa-fw
      %i.fa.fa-caret-down
    %ul.dropdown-menu.dropdown-tasks
      %li
        %a{:href => "#"}
          %div
            %p
              %strong Task 1
              %span.pull-right.text-muted 40% Complete
            .progress.progress-striped.active
              .progress-bar.progress-bar-success{"aria-valuemax" => "100", "aria-valuemin" => "0", "aria-valuenow" => "40", :role => "progressbar", :style => "width: 40%"}
                %span.sr-only 40% Complete (success)
      %li.divider
      %li
        %a{:href => "#"}
          %div
            %p
              %strong Task 2
              %span.pull-right.text-muted 20% Complete
            .progress.progress-striped.active
              .progress-bar.progress-bar-info{"aria-valuemax" => "100", "aria-valuemin" => "0", "aria-valuenow" => "20", :role => "progressbar", :style => "width: 20%"}
                %span.sr-only 20% Complete
      %li.divider
      %li
        %a{:href => "#"}
          %div
            %p
              %strong Task 3
              %span.pull-right.text-muted 60% Complete
            .progress.progress-striped.active
              .progress-bar.progress-bar-warning{"aria-valuemax" => "100", "aria-valuemin" => "0", "aria-valuenow" => "60", :role => "progressbar", :style => "width: 60%"}
                %span.sr-only 60% Complete (warning)
      %li.divider
      %li
        %a{:href => "#"}
          %div
            %p
              %strong Task 4
              %span.pull-right.text-muted 80% Complete
            .progress.progress-striped.active
              .progress-bar.progress-bar-danger{"aria-valuemax" => "100", "aria-valuemin" => "0", "aria-valuenow" => "80", :role => "progressbar", :style => "width: 80%"}
                %span.sr-only 80% Complete (danger)
      %li.divider
      %li
        %a.text-center{:href => "#"}
          %strong See All Tasks
          %i.fa.fa-angle-right
    / /.dropdown-tasks
  / /.dropdown
  %li.dropdown
    %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
      %i.fa.fa-bell.fa-fw
      %i.fa.fa-caret-down
    %ul.dropdown-menu.dropdown-alerts
      %li
        %a{:href => "#"}
          %div
            %i.fa.fa-comment.fa-fw
            New Comment
            %span.pull-right.text-muted.small 4 minutes ago
      %li.divider
      %li
        %a{:href => "#"}
          %div
            %i.fa.fa-twitter.fa-fw
            3 New Followers
            %span.pull-right.text-muted.small 12 minutes ago
      %li.divider
      %li
        %a{:href => "#"}
          %div
            %i.fa.fa-envelope.fa-fw
            Message Sent
            %span.pull-right.text-muted.small 4 minutes ago
      %li.divider
      %li
        %a{:href => "#"}
          %div
            %i.fa.fa-tasks.fa-fw
            New Task
            %span.pull-right.text-muted.small 4 minutes ago
      %li.divider
      %li
        %a{:href => "#"}
          %div
            %i.fa.fa-upload.fa-fw
            Server Rebooted
            %span.pull-right.text-muted.small 4 minutes ago
      %li.divider
      %li
        %a.text-center{:href => "#"}
          %strong See All Alerts
          %i.fa.fa-angle-right
    / /.dropdown-alerts
  / /.dropdown
  %li.dropdown
    %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
      %i.fa.fa-user.fa-fw
      %i.fa.fa-caret-down
    %ul.dropdown-menu.dropdown-user
      - if user_signed_in?
        %li
          %a{:href => "#"}
            %i.fa.fa-user.fa-fw
            User Profile
        %li
          %a{:href => "#"}
            %i.fa.fa-gear.fa-fw
            Settings
        %li.divider
        %li
          = link_to destroy_user_session_path, method: :delete do
            %i.fa.fa-sign-out.fa-fw
            Logout
      - else
        %li
          = link_to new_user_session_path do
            %i.fa.fa-user.fa-fw
            Login
        %li
          = link_to new_user_registration_path do
            %i.fa.fa-gear.fa-fw
            Register
    / /.dropdown-user
  / /.dropdown
/ /.navbar-top-links

app/views/layouts/_sidebar.html.haml
.navbar-default.sidebar{:role => "navigation"}
  .sidebar-nav.navbar-collapse
    %ul#side-menu.nav
      %li.sidebar-search
        .input-group.custom-search-form
          %input.form-control{:placeholder => "Search...", :type => "text"}
            %span.input-group-btn
              %button.btn.btn-default{:type => "button"}
                %i.fa.fa-search
        / /input-group
      %li
        = link_to root_path do
          %i.fa.fa-dashboard.fa-fw
          Dashboard
      %li
        %a{:href => "#"}
          %i.fa.fa-bar-chart-o.fa-fw
          Charts
          %span.fa.arrow
        %ul.nav.nav-second-level
          %li
            = link_to "Flot Charts", flot_path
          %li
            = link_to "Morris.js Charts", morris_path
        / /.nav-second-level
      %li
        = link_to tables_path do
          %i.fa.fa-table.fa-fw
          Tables
      %li
        = link_to forms_path do 
          %i.fa.fa-edit.fa-fw
          Forms
      %li
        %a{:href => "#"}
          %i.fa.fa-wrench.fa-fw
          UI Elements
          %span.fa.arrow
        %ul.nav.nav-second-level
          %li
            = link_to "Panels and Wells", panels_wells_path
          %li
            = link_to "Buttons", buttons_path
          %li
            = link_to "Notifications", notifications_path
          %li
            = link_to "Typography", typography_path
          %li
            = link_to "Icons", icons_path
          %li
            = link_to "Grid", grid_path
        / /.nav-second-level
      %li
        %a{:href => "#"}
          %i.fa.fa-sitemap.fa-fw
          Multi-Level Dropdown
          %span.fa.arrow
        %ul.nav.nav-second-level
          %li
            %a{:href => "#"} Second Level Item
          %li
            %a{:href => "#"} Second Level Item
          %li
            %a{:href => "#"}
              Third Level
              %span.fa.arrow
            %ul.nav.nav-third-level
              %li
                %a{:href => "#"} Third Level Item
              %li
                %a{:href => "#"} Third Level Item
              %li
                %a{:href => "#"} Third Level Item
              %li
                %a{:href => "#"} Third Level Item
            / /.nav-third-level
        / /.nav-second-level
      %li
        %a{:href => "#"}
          %i.fa.fa-files-o.fa-fw
          Sample Pages
          %span.fa.arrow
        %ul.nav.nav-second-level
          %li
            = link_to "Blank Page", blank_path
          %li
            = link_to "Login Page", login_path
        / /.nav-second-level
  / /.sidebar-collapse
/ /.navbar-static-side

app/views/layouts/application.html.haml
!!!
%html{:lang => "en"}
  %head
    %meta{:charset => "utf-8"}
    %meta{:content => "IE=edge", "http-equiv" => "X-UA-Compatible"}
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}
    %meta{:content => "", :name => "description"}
    %meta{:content => "", :name => "author"}
    %title RailsTemplateImport
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags

    / HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries
    / WARNING: Respond.js doesn't work if you view the page via file://
    /[if lt IE 9]
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
  %body
    #wrapper
      / Navigation
      %nav.navbar.navbar-default.navbar-static-top{:role => "navigation", :style => "margin-bottom: 0"}
        = render 'layouts/nav'
        = render 'layouts/sidebar'
      #page-wrapper
        = render 'layouts/alerts' if notice || alert
        = yield
      / /#page-wrapper
    / /#wrapper

app/views/layouts/login.html.haml
!!!
%html{:lang => "en"}
  %head
    %meta{:charset => "utf-8"}
    %meta{:content => "IE=edge", "http-equiv" => "X-UA-Compatible"}
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}
    %meta{:content => "", :name => "description"}
    %meta{:content => "", :name => "author"}
    %title RailsTemplateImport
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags

    / HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries
    / WARNING: Respond.js doesn't work if you view the page via file://
    /[if lt IE 9]
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
  %body
    = render 'layouts/alerts' if notice || alert
  
    = yield

app/views/welcome/blank.html.haml
.container-fluid
  .row
    .col-lg-12
      %h1.page-header Blank
    / /.col-lg-12
  / /.row
/ /.container-fluid

app/views/welcome/buttons.html.haml
.row
  .col-lg-12
    %h1.page-header Buttons
  / /.col-lg-12
/ /.row
.row
  .col-lg-6
    .panel.panel-default
      .panel-heading
        Default Buttons
      / /.panel-heading
      .panel-body
        %h4 Normal Buttons
        %p
          %button.btn.btn-default{:type => "button"} Default
          %button.btn.btn-primary{:type => "button"} Primary
          %button.btn.btn-success{:type => "button"} Success
          %button.btn.btn-info{:type => "button"} Info
          %button.btn.btn-warning{:type => "button"} Warning
          %button.btn.btn-danger{:type => "button"} Danger
          %button.btn.btn-link{:type => "button"} Link
        %br/
        %h4 Disabled Buttons
        %p
          %button.btn.btn-default.disabled{:type => "button"} Default
          %button.btn.btn-primary.disabled{:type => "button"} Primary
          %button.btn.btn-success.disabled{:type => "button"} Success
          %button.btn.btn-info.disabled{:type => "button"} Info
          %button.btn.btn-warning.disabled{:type => "button"} Warning
          %button.btn.btn-danger.disabled{:type => "button"} Danger
          %button.btn.btn-link.disabled{:type => "button"} Link
        %br/
        %h4 Button Sizes
        %p
          %button.btn.btn-primary.btn-lg{:type => "button"} Large button
          %button.btn.btn-primary{:type => "button"} Default button
          %button.btn.btn-primary.btn-sm{:type => "button"} Small button
          %button.btn.btn-primary.btn-xs{:type => "button"} Mini button
          %br/
          %br/
          %button.btn.btn-primary.btn-lg.btn-block{:type => "button"} Block level button
      / /.panel-body
    / /.panel
    .panel.panel-default
      .panel-heading
        Circle Icon Buttons with Font Awesome Icons
      / /.panel-heading
      .panel-body
        %h4 Normal Circle Buttons
        %button.btn.btn-default.btn-circle{:type => "button"}
          %i.fa.fa-check
        %button.btn.btn-primary.btn-circle{:type => "button"}
          %i.fa.fa-list
        %button.btn.btn-success.btn-circle{:type => "button"}
          %i.fa.fa-link
        %button.btn.btn-info.btn-circle{:type => "button"}
          %i.fa.fa-check
        %button.btn.btn-warning.btn-circle{:type => "button"}
          %i.fa.fa-times
        %button.btn.btn-danger.btn-circle{:type => "button"}
          %i.fa.fa-heart
        %br/
        %br/
        %h4 Large Circle Buttons
        %button.btn.btn-default.btn-circle.btn-lg{:type => "button"}
          %i.fa.fa-check
        %button.btn.btn-primary.btn-circle.btn-lg{:type => "button"}
          %i.fa.fa-list
        %button.btn.btn-success.btn-circle.btn-lg{:type => "button"}
          %i.fa.fa-link
        %button.btn.btn-info.btn-circle.btn-lg{:type => "button"}
          %i.fa.fa-check
        %button.btn.btn-warning.btn-circle.btn-lg{:type => "button"}
          %i.fa.fa-times
        %button.btn.btn-danger.btn-circle.btn-lg{:type => "button"}
          %i.fa.fa-heart
        %br/
        %br/
        %h4 Extra Large Circle Buttons
        %button.btn.btn-default.btn-circle.btn-xl{:type => "button"}
          %i.fa.fa-check
        %button.btn.btn-primary.btn-circle.btn-xl{:type => "button"}
          %i.fa.fa-list
        %button.btn.btn-success.btn-circle.btn-xl{:type => "button"}
          %i.fa.fa-link
        %button.btn.btn-info.btn-circle.btn-xl{:type => "button"}
          %i.fa.fa-check
        %button.btn.btn-warning.btn-circle.btn-xl{:type => "button"}
          %i.fa.fa-times
        %button.btn.btn-danger.btn-circle.btn-xl{:type => "button"}
          %i.fa.fa-heart
      / /.panel-body
    / /.panel
  / /.col-lg-6
  .col-lg-6
    .panel.panel-default
      .panel-heading
        Outline Buttons with Smooth Transition
      / /.panel-heading
      .panel-body
        %h4 Outline Buttons
        %p
          %button.btn.btn-outline.btn-default{:type => "button"} Default
          %button.btn.btn-outline.btn-primary{:type => "button"} Primary
          %button.btn.btn-outline.btn-success{:type => "button"} Success
          %button.btn.btn-outline.btn-info{:type => "button"} Info
          %button.btn.btn-outline.btn-warning{:type => "button"} Warning
          %button.btn.btn-outline.btn-danger{:type => "button"} Danger
          %button.btn.btn-outline.btn-link{:type => "button"} Link
        %br/
        %h4 Outline Button Sizes
        %p
          %button.btn.btn-outline.btn-primary.btn-lg{:type => "button"} Large button
          %button.btn.btn-outline.btn-primary{:type => "button"} Default button
          %button.btn.btn-outline.btn-primary.btn-sm{:type => "button"} Small button
          %button.btn.btn-outline.btn-primary.btn-xs{:type => "button"} Mini button
          %br/
          %br/
          %button.btn.btn-outline.btn-primary.btn-lg.btn-block{:type => "button"} Block level button
      / /.panel-body
    / /.panel
    .panel.panel-default
      .panel-heading
        Social Buttons with Font Awesome Icons
      / /.panel-heading
      .panel-body
        %h4 Social Buttons
        %a.btn.btn-block.btn-social.btn-bitbucket
          %i.fa.fa-bitbucket
          Sign in with Bitbucket
        %a.btn.btn-block.btn-social.btn-dropbox
          %i.fa.fa-dropbox
          Sign in with Dropbox
        %a.btn.btn-block.btn-social.btn-facebook
          %i.fa.fa-facebook
          Sign in with Facebook
        %a.btn.btn-block.btn-social.btn-flickr
          %i.fa.fa-flickr
          Sign in with Flickr
        %a.btn.btn-block.btn-social.btn-github
          %i.fa.fa-github
          Sign in with GitHub
        %a.btn.btn-block.btn-social.btn-google-plus
          %i.fa.fa-google-plus
          Sign in with Google
        %a.btn.btn-block.btn-social.btn-instagram
          %i.fa.fa-instagram
          Sign in with Instagram
        %a.btn.btn-block.btn-social.btn-linkedin
          %i.fa.fa-linkedin
          Sign in with LinkedIn
        %a.btn.btn-block.btn-social.btn-pinterest
          %i.fa.fa-pinterest
          Sign in with Pinterest
        %a.btn.btn-block.btn-social.btn-tumblr
          %i.fa.fa-tumblr
          Sign in with Tumblr
        %a.btn.btn-block.btn-social.btn-twitter
          %i.fa.fa-twitter
          Sign in with Twitter
        %a.btn.btn-block.btn-social.btn-vk
          %i.fa.fa-vk
          Sign in with VK
        %hr/
        .text-center
          %a.btn.btn-social-icon.btn-bitbucket
            %i.fa.fa-bitbucket
          %a.btn.btn-social-icon.btn-dropbox
            %i.fa.fa-dropbox
          %a.btn.btn-social-icon.btn-facebook
            %i.fa.fa-facebook
          %a.btn.btn-social-icon.btn-flickr
            %i.fa.fa-flickr
          %a.btn.btn-social-icon.btn-github
            %i.fa.fa-github
          %a.btn.btn-social-icon.btn-google-plus
            %i.fa.fa-google-plus
          %a.btn.btn-social-icon.btn-instagram
            %i.fa.fa-instagram
          %a.btn.btn-social-icon.btn-linkedin
            %i.fa.fa-linkedin
          %a.btn.btn-social-icon.btn-pinterest
            %i.fa.fa-pinterest
          %a.btn.btn-social-icon.btn-tumblr
            %i.fa.fa-tumblr
          %a.btn.btn-social-icon.btn-twitter
            %i.fa.fa-twitter
          %a.btn.btn-social-icon.btn-vk
            %i.fa.fa-vk
      / /.panel-body
    / /.panel
  / /.col-lg-6
/ /.row

app/views/welcome/flot.html.haml
.row
  .col-lg-12
    %h1.page-header Flot
  / /.col-lg-12
/ /.row
.row
  .col-lg-12
    .panel.panel-default
      .panel-heading
        Line Chart Example
      / /.panel-heading
      .panel-body
        .flot-chart
          #flot-line-chart.flot-chart-content
      / /.panel-body
    / /.panel
  / /.col-lg-12
  .col-lg-6
    .panel.panel-default
      .panel-heading
        Pie Chart Example
      / /.panel-heading
      .panel-body
        .flot-chart
          #flot-pie-chart.flot-chart-content
      / /.panel-body
    / /.panel
  / /.col-lg-6
  .col-lg-6
    .panel.panel-default
      .panel-heading
        Multiple Axes Line Chart Example
      / /.panel-heading
      .panel-body
        .flot-chart
          #flot-line-chart-multi.flot-chart-content
      / /.panel-body
    / /.panel
  / /.col-lg-6
  .col-lg-6
    .panel.panel-default
      .panel-heading
        Moving Line Chart Example
      / /.panel-heading
      .panel-body
        .flot-chart
          #flot-line-chart-moving.flot-chart-content
      / /.panel-body
    / /.panel
  / /.col-lg-6
  .col-lg-6
    .panel.panel-default
      .panel-heading
        Bar Chart Example
      / /.panel-heading
      .panel-body
        .flot-chart
          #flot-bar-chart.flot-chart-content
      / /.panel-body
    / /.panel
  / /.col-lg-6
  .col-lg-12
    .panel.panel-default
      .panel-heading
        Flot Charts Usage
      / /.panel-heading
      .panel-body
        %p
          Flot is a pure JavaScript plotting library for jQuery, with a focus on simple usage, attractive looks, and interactive features. In SB Admin, we are using the most recent version of Flot along with a few plugins to enhance the user experience. The Flot plugins being used are the tooltip plugin for hoverable tooltips, and the resize plugin for fully responsive charts. The documentation for Flot Charts is available on their website,
          = succeed "." do
            %a{:href => "http://www.flotcharts.org/", :target => "_blank"} http://www.flotcharts.org/
        %a.btn.btn-default.btn-lg.btn-block{:href => "http://www.flotcharts.org/", :target => "_blank"} View Flot Charts Documentation
      / /.panel-body
    / /.panel
  / /.col-lg-6
/ /.row

%script{src: "/assets/template/flot-data.js"}

app/views/welcome/login.html.haml
.container
  .row
    .col-md-4.col-md-offset-4
      .login-panel.panel.panel-default
        .panel-heading
          %h3.panel-title Please Sign In
        .panel-body
          %form{:role => "form"}
            %fieldset
              .form-group
                %input.form-control{:autofocus => "", :name => "email", :placeholder => "E-mail", :type => "email"}/
              .form-group
                %input.form-control{:name => "password", :placeholder => "Password", :type => "password", :value => ""}/
              .checkbox
                %label
                  %input{:name => "remember", :type => "checkbox", :value => "Remember Me"}>/
                  Remember Me
              / Change this to a button or input when using this as a form
              %a.btn.btn-lg.btn-success.btn-block{:href => "index.html"} Login

app/views/welcome/morris.html.haml
.row
  .col-lg-12
    %h1.page-header Morris.js Charts
  / /.col-lg-12
/ /.row
.row
  .col-lg-6
    .panel.panel-default
      .panel-heading
        Area Chart Example
      / /.panel-heading
      .panel-body
        #morris-area-chart
      / /.panel-body
    / /.panel
  / /.col-lg-6
  .col-lg-6
    .panel.panel-default
      .panel-heading
        Bar Chart Example
      / /.panel-heading
      .panel-body
        #morris-bar-chart
      / /.panel-body
    / /.panel
  / /.col-lg-6
  .col-lg-6
    .panel.panel-default
      .panel-heading
        Line Chart Example
      / /.panel-heading
      .panel-body
        #morris-line-chart
      / /.panel-body
    / /.panel
  / /.col-lg-6
  .col-lg-6
    .panel.panel-default
      .panel-heading
        Donut Chart Example
      / /.panel-heading
      .panel-body
        #morris-donut-chart
      / /.panel-body
    / /.panel
  / /.col-lg-6
  .col-lg-12
    .panel.panel-default
      .panel-heading
        Morris.js Usage
      / /.panel-heading
      .panel-body
        %p
          Morris.js is a jQuery based charting plugin created by Olly Smith. In SB Admin, we are using the most recent version of Morris.js which includes the resize function, which makes the charts fully responsive. The documentation for Morris.js is available on their website,
          = succeed "." do
            %a{:href => "http://morrisjs.github.io/morris.js/", :target => "_blank"} http://morrisjs.github.io/morris.js/
        %a.btn.btn-default.btn-lg.btn-block{:href => "http://morrisjs.github.io/morris.js/", :target => "_blank"} View Morris.js Documentation
      / /.panel-body
    / /.panel
  / /.col-lg-6
/ /.row
%script{src: "/assets/template/morris-data.js"}